- hosts: vyos
  tasks:
    - name: Set Banner
      vyos_banner:
        banner: post-login
        text: "{{ lookup('file', 'banner.txt')}}"

    - name: Setup VLANs
      vyos_vlan:
        vlan_id: "{{ item.vlan_id }}"
        name: "{{ item.name }}"
        interfaces: eth1
      loop:
        - name: Proxy
          vlan_id: 10

        - name: Jump
          vlan_id: 20

        - name: IDS
          vlan_id: 30

        - name: MalwareAnalysis
          vlan_id: 40

        - name: AttackLab
          vlan_id: 50
      loop_control:
        label: "{{ item.name }}"
    
    - name: Setup VLAN gateways
      vyos_l3_interfaces:
        config:
          - name: eth1
            ipv4:
              - address: 10.0.1.1/24
            vifs:
              - vlan_id: 10
                ipv4:
                  - address: 10.0.10.1/24
              - vlan_id: 20
                ipv4:
                  - address: 10.0.20.1/24
              - vlan_id: 30
                ipv4:
                  - address: 10.0.30.1/24
              - vlan_id: 40
                ipv4:
                  - address: 10.0.40.1/24
              - vlan_id: 50
                ipv4:
                  - address: 10.0.50.1/24
        state: replaced

    - name: Setup NAT rules for VLAN1 (Management), VLAN10 (Proxy), VLAN40 (MalwareAnalysis), VLAN50 (AttackLab) for outbound Internet access
      vyos_config:
        save: yes
        lines:
          - set nat source rule 100 outbound-interface 'eth0'
          - set nat source rule 100 source address '10.0.1.0/24'
          - set nat source rule 100 translation address masquerade

          - set nat source rule 110 outbound-interface 'eth0'
          - set nat source rule 110 source address '10.0.10.0/24'
          - set nat source rule 110 translation address masquerade

          
          # Enable only if you intend to use Google Workspace Secure LDAP (sssd seems to have issues with proxying through 10.0.10.10)
          #- set nat source rule 120 outbound-interface 'eth0'
          #- set nat source rule 120 source address '10.0.20.0/24'
          #- set nat source rule 120 translation address masquerade
          #- set nat source rule 120 protocol tcp
          #- set nat source rule 120 destination port 636

          - set nat source rule 140 outbound-interface 'eth0'
          - set nat source rule 140 source address '10.0.40.0/24'
          - set nat source rule 140 translation address masquerade

          - set nat source rule 150 outbound-interface 'eth0'
          - set nat source rule 150 source address '10.0.50.0/24'
          - set nat source rule 150 translation address masquerade

    # enable key-based auth, disable password-auth, but don't delete system user for break-glass access via console
    - name: Configure SSH key-based authentication
      vyos_command:
        commands:
          - configure
          - set system login user {{ vyos_key_username }} authentication public-keys {{ vyos_key_username }}@vyos type ssh-rsa
          - set system login user {{ vyos_key_username }} authentication public-keys {{ vyos_key_username}}@vyos key {{ lookup('file', '../../shared/id_ssh_rsa.pub').split()[1] }}
          - commit

    - name: Set Cloudflare as DNS server and enable DNS forwarding on router
      vyos_command:
        commands:
          - configure
          - set system name-server 1.1.1.1
          - set service dns forwarding listen-address 10.0.10.1
          - set service dns forwarding allow-from 10.0.0.0/8
          - set service dns forwarding system
          - commit

    - name: Enable Squid non-transparent proxy
      vyos_command:
        commands:
          - configure
          - set service webproxy listen-address 10.0.10.1
          - set service webproxy listen-address 10.0.10.1 disable-transparent
          - set service webproxy listen-address 10.0.10.1 port 3127
          - commit

    - name: Enable DHCP server for malware lab
      vyos_command:
        commands:
          - configure
          - set service dhcp-server shared-network-name MalwareNet subnet 10.0.40.0/24 domain-name 'host.{{ lab_domain|trim }}'
          - set service dhcp-server shared-network-name MalwareNet subnet 10.0.40.0/24 dns-server '10.0.10.10'
          - set service dhcp-server shared-network-name MalwareNet subnet 10.0.40.0/24 default-router '10.0.40.1'
          - set service dhcp-server shared-network-name MalwareNet subnet 10.0.40.0/24 range 0 start '10.0.40.100'
          - set service dhcp-server shared-network-name MalwareNet subnet 10.0.40.0/24 range 0 stop '10.0.40.254'
          - commit

    - name: Save configuration
      vyos_command:
        commands:
          - configure
          - save
